export const MIN_TOPICS_PER_DOCUMENT = 5;
export const MAX_TOPICS_PER_DOCUMENT = 12;
export const TARGET_TOPICS_PER_DOCUMENT = 8;

export const MIN_QUESTIONS_PER_TOPIC = 4;
export const MAX_QUESTIONS_PER_TOPIC = 8;
export const TARGET_QUESTIONS_PER_TOPIC = 6;

export const MIN_MULTIPLE_CHOICE_PER_TOPIC = 1;
export const MAX_MULTIPLE_CHOICE_PER_TOPIC = 3;

export const QUESTION_RETRIEVAL_LIMIT = 10;
export const QUESTION_GENERATION_CONCURRENCY = 2;
